spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-cloud-gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - TokenRelay
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/files/**
          filters:
            - TokenRelay
        - id: public-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/public/**
        - id: authorization-server-route
          uri: lb://authorization-server
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}

    stream:
      kafka:
        binder:
          brokers: 68.183.225.48:9092
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
    loadbalancer:
      stats:
        micrometer:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://68.183.225.48:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
